// The platform-wide user list an admin sees on /admin — shaped like the real
// Mongoose User schema (role, balance, activeDeposit[], totalDeposit,
// totalWithdraw, suspended, createdAt, wallet ids, etc.) so a real fetch is a
// drop-in swap. u_1 (amara_o) mirrors the investor-side mockUser.js exactly —
// same person, viewed from the admin side.

const daysAgo = (n) => new Date(Date.now() - n * 86400000).toISOString();

export const mockUsers = [
  {
    id: "u_1",
    username: "amara_o",
    email: "amara@example.com",
    role: "user",
    referredby: null, // joined directly, not via a referral link
    number: "+1 415 555 0132",
    country: "United States",
    balance: 12480.65,
    totalDeposit: 15500,
    totalWithdraw: 3200,
    minimumWithdrawal: 0,
    promoBonus: 0,
    verified: true,
    suspended: false,
    createdAt: daysAgo(210),
    bitcoinAccountId: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
    bitcoinNetwork: "",
    ethereumAccountId: "",
    ethereumNetwork: "",
    litecoinAccountId: "",
    litecoinNetwork: "",
    dogeAccountId: "",
    dogeNetwork: "",
    usdtAccountId: "TXn9k2FqZ8mR4dP1vC7yB3xW6sL0uAq4kQ2",
    usdtNetwork: "TRC-20",
    activeDeposit: [
      { id: "ad_1", plan: "Standard Plan", amount: 5000, profit: 340.2, method: "USDT", date: daysAgo(14), stopped: false, withdrawn: false, balanceDeductedAmount: 0, balanceFixed: false },
      { id: "ad_2", plan: "Silver Plan", amount: 10000, profit: 812.4, method: "BTC", date: daysAgo(35), stopped: false, withdrawn: false, balanceDeductedAmount: 0, balanceFixed: false },
      { id: "ad_3", plan: "Basic Plan", amount: 500, profit: 61.05, method: "USDT", date: daysAgo(32), stopped: true, withdrawn: false, balanceDeductedAmount: 0, balanceFixed: false },
    ],
  },
  {
    id: "u_2",
    username: "jasmine_k",
    email: "jasmine.k@example.com",
    role: "user",
    referredby: "amara_o",
    number: "+44 7700 900123",
    country: "United Kingdom",
    balance: 3260,
    totalDeposit: 3000,
    totalWithdraw: 0,
    minimumWithdrawal: 0,
    promoBonus: 0,
    verified: true,
    suspended: false,
    createdAt: daysAgo(180),
    bitcoinAccountId: "",
    bitcoinNetwork: "",
    ethereumAccountId: "0x8f3CE2A1b9d4E6c7F0a1B2c3D4e5F6a7B8c9D0e1",
    ethereumNetwork: "ERC-20",
    litecoinAccountId: "",
    litecoinNetwork: "",
    dogeAccountId: "",
    dogeNetwork: "",
    usdtAccountId: "",
    usdtNetwork: "",
    activeDeposit: [
      { id: "ad_4", plan: "Standard Plan", amount: 3000, profit: 260, method: "ETH", date: daysAgo(45), stopped: false, withdrawn: false, balanceDeductedAmount: 0, balanceFixed: false },
    ],
  },
  {
    id: "u_3",
    username: "marcus_t",
    email: "marcus.t@example.com",
    role: "user",
    referredby: "amara_o",
    number: "+1 646 555 0110",
    country: "Canada",
    balance: 820.4,
    totalDeposit: 800,
    totalWithdraw: 0,
    minimumWithdrawal: 0,
    promoBonus: 0,
    verified: true,
    suspended: false,
    createdAt: daysAgo(150),
    bitcoinAccountId: "",
    bitcoinNetwork: "",
    ethereumAccountId: "",
    ethereumNetwork: "",
    litecoinAccountId: "",
    litecoinNetwork: "",
    dogeAccountId: "",
    dogeNetwork: "",
    usdtAccountId: "",
    usdtNetwork: "",
    activeDeposit: [{ id: "ad_5", plan: "Basic Plan", amount: 800, profit: 42.4, method: "USDT", date: daysAgo(20), stopped: false, withdrawn: false, balanceDeductedAmount: 0, balanceFixed: false }],
  },
  {
    id: "u_4",
    username: "priya_s",
    email: "priya.s@example.com",
    role: "user",
    referredby: "amara_o",
    number: "+91 98200 12345",
    country: "India",
    balance: 22100,
    totalDeposit: 20000,
    totalWithdraw: 0,
    minimumWithdrawal: 0,
    promoBonus: 0,
    verified: true,
    suspended: false,
    createdAt: daysAgo(120),
    bitcoinAccountId: "",
    bitcoinNetwork: "",
    ethereumAccountId: "",
    ethereumNetwork: "",
    litecoinAccountId: "",
    litecoinNetwork: "",
    dogeAccountId: "",
    dogeNetwork: "",
    usdtAccountId: "TXn9k2FqZ8mR4dP1vC7yB3xW6sL0uAq4kQ2",
    usdtNetwork: "TRC-20",
    activeDeposit: [{ id: "ad_6", plan: "Silver Plan", amount: 20000, profit: 1840, method: "USDT", date: daysAgo(60), stopped: false, withdrawn: false, balanceDeductedAmount: 0, balanceFixed: false }],
  },
  {
    id: "u_5",
    username: "dwayne_f",
    email: "dwayne.f@example.com",
    role: "user",
    referredby: "amara_o",
    number: "+1 213 555 0148",
    country: "United States",
    balance: 150,
    totalDeposit: 500,
    totalWithdraw: 400,
    minimumWithdrawal: 0,
    promoBonus: 0,
    verified: true,
    suspended: true,
    restrictionMessage: "Account under review after a chargeback dispute.",
    createdAt: daysAgo(300),
    bitcoinAccountId: "",
    bitcoinNetwork: "",
    ethereumAccountId: "",
    ethereumNetwork: "",
    litecoinAccountId: "",
    litecoinNetwork: "",
    dogeAccountId: "",
    dogeNetwork: "",
    usdtAccountId: "",
    usdtNetwork: "",
    // Reinvested $300 from balance into Basic Plan; the plan matured and
    // stopped, but the reinvested principal was never returned to balance —
    // this is what the admin's "Fix Balance" action is for.
    activeDeposit: [{ id: "ad_7", plan: "Basic Plan", amount: 300, profit: 18.5, method: "reinvestment", date: daysAgo(45), stopped: true, withdrawn: false, balanceDeductedAmount: 300, balanceFixed: false }],
  },
  {
    id: "u_6",
    username: "chidi_o",
    email: "chidi.o@example.com",
    role: "user",
    referredby: "amara_o",
    number: "+234 802 555 0110",
    country: "Nigeria",
    balance: 5600,
    totalDeposit: 5000,
    totalWithdraw: 0,
    minimumWithdrawal: 0,
    promoBonus: 0,
    verified: true,
    suspended: false,
    createdAt: daysAgo(60),
    bitcoinAccountId: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
    bitcoinNetwork: "Bitcoin",
    ethereumAccountId: "",
    ethereumNetwork: "",
    litecoinAccountId: "",
    litecoinNetwork: "",
    dogeAccountId: "",
    dogeNetwork: "",
    usdtAccountId: "",
    usdtNetwork: "",
    activeDeposit: [{ id: "ad_8", plan: "Standard Plan", amount: 5000, profit: 600, method: "BTC", date: daysAgo(30), stopped: false, withdrawn: false, balanceDeductedAmount: 0, balanceFixed: false }],
  },
  {
    id: "u_7",
    username: "lena_m",
    email: "lena.m@example.com",
    role: "user",
    referredby: "amara_o",
    number: "",
    country: "",
    balance: 0,
    totalDeposit: 0,
    totalWithdraw: 0,
    minimumWithdrawal: 0,
    promoBonus: 0,
    verified: false,
    suspended: false,
    createdAt: daysAgo(4),
    bitcoinAccountId: "",
    bitcoinNetwork: "",
    ethereumAccountId: "",
    ethereumNetwork: "",
    litecoinAccountId: "",
    litecoinNetwork: "",
    dogeAccountId: "",
    dogeNetwork: "",
    usdtAccountId: "",
    usdtNetwork: "",
    activeDeposit: [],
  },
  {
    id: "u_8",
    username: "sam_r",
    email: "sam.r@example.com",
    role: "user",
    referredby: "amara_o",
    number: "+61 4 5555 0110",
    country: "Australia",
    balance: 4100,
    totalDeposit: 4000,
    totalWithdraw: 200,
    minimumWithdrawal: 0,
    promoBonus: 50,
    verified: true,
    suspended: false,
    createdAt: daysAgo(90),
    bitcoinAccountId: "",
    bitcoinNetwork: "",
    ethereumAccountId: "",
    ethereumNetwork: "",
    litecoinAccountId: "",
    litecoinNetwork: "",
    dogeAccountId: "",
    dogeNetwork: "",
    usdtAccountId: "",
    usdtNetwork: "",
    activeDeposit: [{ id: "ad_9", plan: "Basic Plan", amount: 4000, profit: 300, method: "USDT", date: daysAgo(25), stopped: false, withdrawn: false, balanceDeductedAmount: 0, balanceFixed: false }],
  },
  {
    id: "u_9",
    username: "tosin_a",
    email: "tosin.a@example.com",
    role: "admin",
    referredby: "amara_o",
    number: "+1 917 555 0177",
    country: "United States",
    balance: 0,
    totalDeposit: 0,
    totalWithdraw: 0,
    minimumWithdrawal: 0,
    promoBonus: 0,
    verified: true,
    suspended: false,
    createdAt: daysAgo(400),
    bitcoinAccountId: "",
    bitcoinNetwork: "",
    ethereumAccountId: "",
    ethereumNetwork: "",
    litecoinAccountId: "",
    litecoinNetwork: "",
    dogeAccountId: "",
    dogeNetwork: "",
    usdtAccountId: "",
    usdtNetwork: "",
    activeDeposit: [],
  },
];

export function getUserById(id) {
  return mockUsers.find((u) => u.id === id) || null;
}

export function getUnreturnedReinvestment(user) {
  return (user.activeDeposit || []).filter((d) => d.stopped && !d.balanceFixed).reduce((sum, d) => sum + (d.balanceDeductedAmount || 0), 0);
}
